spring.application.name=inventory-service
server.port=8082

spring.datasource.url=${DATASOURCE_URL:jdbc:postgresql://localhost:5434/inventory_service_db}
spring.datasource.username=${DATASOURCE_USERNAME:username}
spring.datasource.password=${DATASOURCE_PASSWORD:password}

spring.jpa.hibernate.ddl-auto=none
