spring.application.name=inventory-service
server.port=8082

spring.datasource.url=jdbc:postgresql://inventory-db:5432/inventory_service_db
spring.datasource.username=username
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=none
