spring.application.name=product-service
server.port=8081

spring.datasource.url=jdbc:postgresql://product-db:5432/product_service_db
spring.datasource.username=username
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=none

cloudinary.cloud.name=${CLOUD_NAME}
cloudinary.api.key=${API_KEY}
cloudinary.api.secret=${API_SECRET}
